repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        additional_dependencies: [pylint]
        args: [--rcfile=pylintrc]
        entry: uv run --active pylint 