tonggpt:
  api_version: "2024-02-01"
  api_base: "https://api.tonggpt.mybigai.ac.cn/proxy"
  region: "eastus2"
  model_name: "gpt-4o-2024-08-06"

tool:
  api_version: "2024-02-01"
  api_base: "https://api.tonggpt.mybigai.ac.cn/proxy"
  region: "eastus2"
  model_name: "gpt-4o-2024-08-06"

