llm:
  provider: "azure" # azure, openai, anthropic
  azure:
    endpoint: "https://api.tonggpt.mybigai.ac.cn/proxy/eastus2"
    model: "gpt-4o-2024-08-06"
  openai:
    model: "gpt-4o"
    endpoint: "https://cfcus02.opapi.win/v1"
  anthropic:
    model: "claude-3-7-sonnet-20250219"
    endpoint: "https://cfcus02.opapi.win"
  qwen:
    model: "qwen-max-latest"
    endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1"
