exclude:
  - macosagent
  - tests
  - examples

remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Getting Started:
    - Introduction: ''
  - Examples:
    - Markdown: docs/examples